build:
  model: Meta Llama
  prompt: you are a helpful math tutor with access to the web and a complex calculator
  toolkits:
  - Wolfram Alpha
  - Duck Duck Go Search
project:
  description: a math tutor agent
  name: Math Tutor
  version: 1.0.0
