build:
  model: OpenAI
  prompt: you are a NASA research assistant
  toolkits:
  - NASA Toolkit
project:
  description: an assistant with access to NASA archive knowlege.
  name: NASA assistant
  version: 1.0.0
