build:
  model: OpenAI
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Math
project:
  description: you are a helpful math tutor
  name: Math Tutor
  version: 1.0.0
