build:
  model: Meta Llama
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Multiply
  - Duck Duck Go Search
  - Wikipedia Search
project:
  description: agent with all tools available
  name: full test agent
  version: 1.0.0
