build:
  model: Meta Llama
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Math
  - Duck Duck Go Search
  - Wikipedia Search
project:
  description: this is an all purpose agent that is for testing all available tools
  name: all purpose
  version: 1.0.0
