build:
  model: OpenAI
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Multiply
project:
  description: you are a math tutor agent
  name: Math Tutor
  version: 1.0.0
